const data = [
    { name: "anchor", image: "anchor-solid.svg" },
    { name: "atom", image: "atom-solid.svg" },
    { name: "bolt-lightning", image: "bolt-lightning-solid.svg" },
    { name: "bomb", image: "bomb-solid.svg" },
    { name: "book", image: "book-solid.svg" },
    { name: "carrot", image: "carrot-solid.svg" },
    { name: "cat", image: "cat-solid.svg" },
    { name: "crow", image: "crow-solid.svg" },
    { name: "fish", image: "fish-solid.svg" },
    { name: "flask", image: "flask-solid.svg" },
    { name: "hat-wizard", image: "hat-wizard-solid.svg" },
    { name: "jet-fighter-up", image: "jet-fighter-up-solid.svg" },
    { name: "lightbulb", image: "lightbulb-solid.svg" },
    { name: "meteor", image: "meteor-solid.svg" },
    { name: "moon", image: "moon-solid.svg" },
    { name: "star", image: "star-solid.svg" },
    { name: "terminal", image: "terminal-solid.svg" },
    { name: "tree", image: "tree-solid.svg" },
]